name: Orquestador de infraestructuraa

on:
  push:
    branches:
      - main

jobs:
  orquestar-todo:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Clonar FEGF-project
        uses: actions/checkout@v3
        with:
          repository: GaryFernandoYM/FEGF-project
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: project

      - name: Clonar FEGF-s3
        uses: actions/checkout@v3
        with:
          repository: GaryFernandoYM/FEGF-s3
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: s3

      - name: Deploy S3 con Terraform
        run: |
          cd s3
          terraform init
          terraform apply -auto-approve -var="bucket_name=bucket-lambda-s3-fegf"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Subir archivo CSV al bucket S3
        run: |
          aws s3 cp ./project/csv/kc_house_datcsv.csv s3://bucket-lambda-s3-fegf/

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1