name: Orquestador de infraestructur

on:
  push:
    branches:
      - main

jobs:
  orquestar-todo:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Clonar FEGF-lambda
        uses: actions/checkout@v3
        with:
          repository: GaryFernandoYM/FEGF-lambda
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: lambda

      - name: Clonar FEGF-s3
        uses: actions/checkout@v3
        with:
          repository: GaryFernandoYM/FEGF-s3
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: s3

      - name: Clonar FEGF-ec2
        uses: actions/checkout@v3
        with:
          repository: GaryFernandoYM/FEGF-ec2
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ec2

      - name: Deploy S3 con Terraform
        run: |
          cd s3
          terraform init
          terraform apply -auto-approve -var="bucket_name=bucket-lambda-s3-fegf"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Crear function.zip para Lambda
        run: |
          cd lambda
          zip function.zip *.py

      - name: Deploy Lambda con Terraform
        run: |
          cd lambda
          terraform init
          terraform apply -auto-approve -var="bucket_name=bucket-lambda-s3-fegf" \
            -var="function_name=lambda-s3-fegf"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Obtener IP pública de EC2
        id: ec2_ip
        working-directory: ec2
        run: |
          IP=$(terraform output -raw public_ip | head -n 1 | tr -d '\n')
          echo "public_ip=$IP" >> "$GITHUB_OUTPUT"
      # Después del apply de EC2
      - name: Subir clave privada como artifact
        uses: actions/upload-artifact@v4
        with:
          name: ec2-private-key
          path: ec2/generated_key.pem

      # Instalar netcat (necesario para esperar puerto 22)
      - name: Instalar netcat
        run: sudo apt-get update -y && sudo apt-get install -y netcat-openbsd

      # Esperar que EC2 esté activa (SSH disponible)
      - name: Esperar que EC2 esté lista
        run: |
          for i in {1..15}; do
            nc -z ${{ steps.ec2_ip.outputs.public_ip }} 22 && echo "✅ EC2 activa" && break
            echo "⏳ Esperando que EC2 esté disponible..."; sleep 5
          done

      # Descargar el archivo .pem generado por Terraform
      - name: Descargar clave privada desde artifact
        uses: actions/download-artifact@v4
        with:
          name: ec2-private-key
          path: ./key

      # Ajustar permisos para que el archivo sea válido para SSH
      - name: Ajustar permisos a la clave privada
        run: chmod 400 ./key/generated_key.pem

      # Conexión vía SSH y clonación del repositorio
      - name: Conectarse y clonar proyecto en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.ec2_ip.outputs.public_ip }}
          username: ubuntu
          key_path: ./key/generated_key.pem
          script: |
            sudo apt-get update -y
            sudo apt-get install -y git
            cd /home/ubuntu
            git clone https://github.com/GaryFernandoYM/Producer.git

